import bpy
from .api_client import SculptorApiClient
from .executor import execute_blender_code

class SculptorProperties(bpy.types.PropertyGroup):
    prompt: bpy.props.StringProperty(
        name="Prompt",
        description="Describe what you want SculptorAI to build in Blender",
        default="Create a low-poly wooden table with 4 legs",
    )
    generated_code: bpy.props.StringProperty(
        name="Generated Code",
        description="Executable Blender Python generated by SculptorAI",
        default="",
    )
    plan_summary: bpy.props.StringProperty(
        name="Plan Summary",
        description="High level overview of the generated plan",
        default="",
    )
    last_status: bpy.props.StringProperty(
        name="Status",
        default="Ready",
    )
    last_error: bpy.props.StringProperty(
        name="Last Error",
        default="",
    )
    is_busy: bpy.props.BoolProperty(
        name="Is Busy",
        default=False,
    )
    active_execution_id: bpy.props.StringProperty(
        name="Execution ID",
        default="",
    )

class SCULPTOR_OT_test_connection(bpy.types.Operator):
    bl_idname = "sculptor.test_connection"
    bl_label = "Test Connection"
    bl_description = "Check connection to the SculptorAI server"

    def execute(self, context):
        props = context.scene.sculptor_props
        props.last_status = "Connecting..."
        ok, res = SculptorApiClient.test_connection(context)
        if ok:
            props.last_status = "Connected"
            self.report({'INFO'}, "Successfully connected to SculptorAI server.")
        else:
            props.last_status = "Connection Failed"
            props.last_error = res.get("error", "Unable to connect")
            self.report({'ERROR'}, f"Connection failed: {props.last_error}")
        return {'FINISHED'}

class SCULPTOR_OT_generate(bpy.types.Operator):
    bl_idname = "sculptor.generate"
    bl_label = "Generate Model"
    bl_description = "Send prompt to SculptorAI to produce a modeling plan and Blender Python"

    def execute(self, context):
        props = context.scene.sculptor_props
        if not props.prompt.strip():
            self.report({'WARNING'}, "Please enter a prompt first.")
            return {'CANCELLED'}

        props.is_busy = True
        props.last_status = "Generating..."
        props.last_error = ""

        blender_ver = f"{bpy.app.version[0]}.{bpy.app.version[1]}"
        ok, res = SculptorApiClient.generate(props.prompt, blender_version=blender_ver, context=context)

        props.is_busy = False
        if ok and "code" in res:
            props.generated_code = res["code"].get("content", "")
            props.plan_summary = res.get("plan", {}).get("summary", "Plan generated successfully")
            props.last_status = "Code Ready (Requires Approval)"
            props.active_execution_id = res.get("generationId", "")
            self.report({'INFO'}, "Generated Blender script ready. Review and Approve.")
        else:
            props.last_status = "Generation Failed"
            props.last_error = res.get("error", "Unknown generation error")
            self.report({'ERROR'}, f"Generation failed: {props.last_error}")

        return {'FINISHED'}

class SCULPTOR_OT_approve_and_run(bpy.types.Operator):
    bl_idname = "sculptor.approve_and_run"
    bl_label = "Approve & Run in Blender"
    bl_description = "Explicitly approve and execute the generated Blender Python script"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        props = context.scene.sculptor_props
        code = props.generated_code
        if not code.strip():
            self.report({'WARNING'}, "No code available to run. Generate or paste code first.")
            return {'CANCELLED'}

        props.is_busy = True
        props.last_status = "Executing in Blender..."

        # Execute code inside Blender runtime
        exec_result = execute_blender_code(code)

        props.is_busy = False
        if exec_result["success"]:
            props.last_status = "Execution Successful"
            props.last_error = ""
            self.report({'INFO'}, f"Script executed successfully in {exec_result['duration_ms']}ms.")
            # Report result to SculptorAI server
            SculptorApiClient.report_execution_result(
                props.active_execution_id,
                status="success",
                stdout=exec_result["stdout"],
                stderr="",
                duration_ms=exec_result["duration_ms"],
                context=context
            )
        else:
            props.last_status = "Execution Error"
            props.last_error = exec_result["error"]
            self.report({'ERROR'}, "Blender execution error encountered.")
            # Report failure to server
            SculptorApiClient.report_execution_result(
                props.active_execution_id,
                status="error",
                stdout=exec_result["stdout"],
                stderr=exec_result["error"],
                duration_ms=exec_result["duration_ms"],
                context=context
            )

        return {'FINISHED'}

class SCULPTOR_OT_fix_error(bpy.types.Operator):
    bl_idname = "sculptor.fix_error"
    bl_label = "Fix with AI"
    bl_description = "Send traceback and script to SculptorAI to automatically diagnose and repair"

    def execute(self, context):
        props = context.scene.sculptor_props
        if not props.last_error.strip():
            self.report({'WARNING'}, "No error traceback found to fix.")
            return {'CANCELLED'}

        props.is_busy = True
        props.last_status = "Diagnosing with AI..."

        blender_ver = f"{bpy.app.version[0]}.{bpy.app.version[1]}"
        ok, res = SculptorApiClient.debug_error(
            props.last_error,
            props.generated_code,
            blender_version=blender_ver,
            context=context
        )

        props.is_busy = False
        if ok and "correctedCode" in res:
            props.generated_code = res["correctedCode"]
            diagnosis = res.get("diagnosis", {})
            props.plan_summary = f"Fix: {diagnosis.get('suggestedFix', 'Applied correction')}"
            props.last_status = "Corrected Code Ready (Requires Approval)"
            props.last_error = ""
            self.report({'INFO'}, "AI provided corrected script. Review and click Approve & Run.")
        else:
            props.last_status = "Fix Failed"
            props.last_error = res.get("error", "Unable to generate correction")
            self.report({'ERROR'}, f"AI diagnosis failed: {props.last_error}")

        return {'FINISHED'}

class SCULPTOR_OT_clear(bpy.types.Operator):
    bl_idname = "sculptor.clear"
    bl_label = "Reset"
    bl_description = "Clear current prompt, code, and errors"

    def execute(self, context):
        props = context.scene.sculptor_props
        props.generated_code = ""
        props.plan_summary = ""
        props.last_status = "Ready"
        props.last_error = ""
        return {'FINISHED'}
