import bpy
from .api_client import SculptorApiClient
from .executor import execute_blender_code
from .compat import get_blender_version_string

class SculptorProperties(bpy.types.PropertyGroup):
    prompt: bpy.props.StringProperty(
        name="Prompt",
        description="Describe what you want SculptorAI to build in Blender",
        default="Create a low-poly wooden table with 4 legs",
    )
    generated_code: bpy.props.StringProperty(
        name="Generated Code",
        description="Executable Blender Python generated by SculptorAI",
        default="",
    )
    plan_summary: bpy.props.StringProperty(
        name="Plan Summary",
        description="High level overview of the generated plan",
        default="",
    )
    last_status: bpy.props.StringProperty(
        name="Status",
        default="Ready",
    )
    last_error: bpy.props.StringProperty(
        name="Last Error",
        default="",
    )
    is_busy: bpy.props.BoolProperty(
        name="Is Busy",
        default=False,
    )
    active_execution_id: bpy.props.StringProperty(
        name="Execution ID",
        default="",
    )
    active_project_id: bpy.props.StringProperty(
        name="Project ID",
        description="Currently active SculptorAI project ID",
        default="default_project",
    )
    auto_heartbeat: bpy.props.BoolProperty(
        name="Auto Heartbeat",
        description="Automatically report connection and status to SculptorAI Studio",
        default=True,
    )


class SCULPTOR_OT_test_connection(bpy.types.Operator):
    bl_idname = "sculptor.test_connection"
    bl_label = "Test Connection"
    bl_description = "Check connection to the SculptorAI server"

    def execute(self, context):
        props = context.scene.sculptor_props
        props.last_status = "Connecting..."
        ok, res = SculptorApiClient.test_connection(context)
        if ok:
            props.last_status = "Connected"
            self.report({'INFO'}, "Successfully connected to SculptorAI server.")
        else:
            props.last_status = "Connection Failed"
            props.last_error = res.get("error", "Unable to connect")
            self.report({'ERROR'}, f"Connection failed: {props.last_error}")
        return {'FINISHED'}

class SCULPTOR_OT_generate(bpy.types.Operator):
    bl_idname = "sculptor.generate"
    bl_label = "Generate Model"
    bl_description = "Send prompt to SculptorAI to produce a modeling plan and Blender Python"

    def execute(self, context):
        props = context.scene.sculptor_props
        if not props.prompt.strip():
            self.report({'WARNING'}, "Please enter a prompt first.")
            return {'CANCELLED'}

        props.is_busy = True
        props.last_status = "Generating..."
        props.last_error = ""

        blender_ver = get_blender_version_string()
        ok, res = SculptorApiClient.generate(props.prompt, blender_version=blender_ver, context=context)

        props.is_busy = False
        if ok and "code" in res:
            props.generated_code = res["code"].get("content", "")
            props.plan_summary = res.get("plan", {}).get("summary", "Plan generated successfully")
            props.last_status = "Code Ready (Requires Approval)"
            props.active_execution_id = res.get("generationId", "")
            self.report({'INFO'}, "Generated Blender script ready. Review and Approve.")
        else:
            props.last_status = "Generation Failed"
            props.last_error = res.get("error", "Unknown generation error")
            self.report({'ERROR'}, f"Generation failed: {props.last_error}")

        return {'FINISHED'}

class SCULPTOR_OT_approve_and_run(bpy.types.Operator):
    bl_idname = "sculptor.approve_and_run"
    bl_label = "Approve & Run in Blender"
    bl_description = "Explicitly approve and execute the generated Blender Python script"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        props = context.scene.sculptor_props
        code = props.generated_code
        if not code.strip():
            self.report({'WARNING'}, "No code available to run. Generate or claim a task first.")
            return {'CANCELLED'}

        props.is_busy = True
        props.last_status = "Executing in Blender..."

        # Signal server that execution is running
        if props.active_execution_id:
            SculptorApiClient.start_task(props.active_execution_id, context=context)

        # Execute code inside Blender runtime with undo support
        exec_result = execute_blender_code(code)

        props.is_busy = False
        if exec_result["success"]:
            props.last_status = "Execution Successful"
            props.last_error = ""
            self.report({'INFO'}, f"Script executed successfully in {exec_result['duration_ms']}ms.")
            
            # Report real result back to SculptorAI server
            if props.active_execution_id:
                SculptorApiClient.report_execution_result(
                    props.active_execution_id,
                    status="success",
                    stdout=exec_result["stdout"],
                    stderr="",
                    duration_ms=exec_result["duration_ms"],
                    context=context
                )
        else:
            props.last_status = "Execution Error"
            props.last_error = exec_result["error"]
            self.report({'ERROR'}, "Blender execution error encountered.")
            
            # Report real failure back to SculptorAI server
            if props.active_execution_id:
                SculptorApiClient.report_execution_result(
                    props.active_execution_id,
                    status="error",
                    stdout=exec_result["stdout"],
                    stderr=exec_result["error"],
                    duration_ms=exec_result["duration_ms"],
                    context=context
                )

        return {'FINISHED'}

class SCULPTOR_OT_fix_error(bpy.types.Operator):
    bl_idname = "sculptor.fix_error"
    bl_label = "Fix with AI"
    bl_description = "Send traceback and script to SculptorAI to automatically diagnose and repair"

    def execute(self, context):
        props = context.scene.sculptor_props
        if not props.last_error.strip():
            self.report({'WARNING'}, "No error traceback found to fix.")
            return {'CANCELLED'}

        props.is_busy = True
        props.last_status = "Diagnosing with AI..."

        blender_ver = get_blender_version_string()
        ok, res = SculptorApiClient.debug_error(
            props.last_error,
            props.generated_code,
            blender_version=blender_ver,
            context=context
        )

        props.is_busy = False
        if ok and "correctedCode" in res:
            props.generated_code = res["correctedCode"]
            diagnosis = res.get("diagnosis", {})
            props.plan_summary = f"Fix: {diagnosis.get('suggestedFix', 'Applied correction')}"
            props.last_status = "Corrected Code Ready (Requires Approval)"
            props.last_error = ""
            self.report({'INFO'}, "AI provided corrected script. Review and click Approve & Run.")
        else:
            props.last_status = "Fix Failed"
            props.last_error = res.get("error", "Unable to generate correction")
            self.report({'ERROR'}, f"AI diagnosis failed: {props.last_error}")

        return {'FINISHED'}

class SCULPTOR_OT_clear(bpy.types.Operator):
    bl_idname = "sculptor.clear"
    bl_label = "Reset"
    bl_description = "Clear current prompt, code, and errors"

    def execute(self, context):
        props = context.scene.sculptor_props
        props.generated_code = ""
        props.plan_summary = ""
        props.last_status = "Ready"
        props.last_error = ""
        props.active_execution_id = ""
        return {'FINISHED'}

class SCULPTOR_OT_fetch_task(bpy.types.Operator):
    bl_idname = "sculptor.fetch_task"
    bl_label = "Claim Web Task"
    bl_description = "Atomically claim pending execution task dispatched from the SculptorAI Web Studio"

    def execute(self, context):
        props = context.scene.sculptor_props
        props.last_status = "Claiming Web Task..."
        ok, task = SculptorApiClient.claim_next_task(context)

        if ok and task:
            props.active_execution_id = task.get("id", "")
            props.generated_code = task.get("script", "")
            props.plan_summary = task.get("prompt", "Task claimed from Web Studio")
            # MANDATORY RULE: Never automatically execute a claimed task. Human must review & approve.
            props.last_status = "Claimed (Requires User Approval)"
            self.report({'INFO'}, f"Claimed task: '{props.plan_summary}'. Review code and click Approve & Run.")
        elif ok and not task:
            props.last_status = "Connected (No Pending Tasks)"
            self.report({'INFO'}, "No pending execution requests in queue.")
        else:
            props.last_status = "Claim Failed"
            self.report({'WARNING'}, "Could not claim task from server.")
        return {'FINISHED'}

def extract_compact_scene_snapshot(context):
    """
    Extracts a lightweight (<10KB) representation of the active Blender scene.
    """
    objects_data = []
    for obj in bpy.data.objects:
        if obj.hide_viewport:
            continue
        dim = [round(v, 3) for v in obj.dimensions] if hasattr(obj, "dimensions") else [0, 0, 0]
        obj_info = {
            "name": obj.name,
            "type": obj.type,
            "location": [round(v, 3) for v in obj.location],
            "rotation": [round(v, 3) for v in obj.rotation_euler],
            "scale": [round(v, 3) for v in obj.scale],
            "dimensions": dim,
            "materials": [slot.material.name for slot in obj.material_slots if slot.material],
            "modifiers": [m.type for m in obj.modifiers],
            "collection": obj.users_collection[0].name if obj.users_collection else "Scene Collection"
        }
        objects_data.append(obj_info)

    return {
        "sceneName": context.scene.name,
        "blenderVersion": get_blender_version_string(),
        "objects": objects_data,
        "activeObject": context.active_object.name if context.active_object else None,
        "selectedObjects": [o.name for o in context.selected_objects],
        "cameras": [o.name for o in bpy.data.objects if o.type == 'CAMERA'],
        "lights": [o.name for o in bpy.data.objects if o.type == 'LIGHT'],
        "collections": [c.name for c in bpy.data.collections]
    }

class SCULPTOR_OT_send_snapshot(bpy.types.Operator):
    bl_idname = "sculptor.send_snapshot"
    bl_label = "Send Scene Snapshot"
    bl_description = "Capture and send compact scene hierarchy to SculptorAI Studio for scene-aware AI editing"

    def execute(self, context):
        props = context.scene.sculptor_props
        props.last_status = "Capturing Scene..."

        snapshot = extract_compact_scene_snapshot(context)
        project_id = props.active_project_id or "default_project"

        ok, res = SculptorApiClient.send_snapshot(project_id, snapshot, context=context)
        if ok:
            props.last_status = "Scene Snapshot Synced"
            self.report({'INFO'}, f"Synced snapshot ({len(snapshot['objects'])} objects) to SculptorAI.")
        else:
            props.last_status = "Snapshot Sync Failed"
            props.last_error = res.get("error", "Failed to send scene snapshot")
            self.report({'WARNING'}, f"Snapshot failed: {props.last_error}")

        return {'FINISHED'}

class SCULPTOR_OT_send_heartbeat(bpy.types.Operator):
    bl_idname = "sculptor.send_heartbeat"
    bl_label = "Send Heartbeat"
    bl_description = "Ping the SculptorAI server to report active connection and workstation status"

    def execute(self, context):
        props = context.scene.sculptor_props
        status = "BUSY" if props.is_busy else "IDLE"
        ok, res = SculptorApiClient.send_heartbeat(
            status=status,
            current_project=props.active_project_id,
            current_execution=props.active_execution_id,
            context=context
        )
        if ok:
            props.last_status = "Connected"
            self.report({'INFO'}, "Heartbeat acknowledged by server.")
        else:
            props.last_status = "Heartbeat Failed"
            self.report({'WARNING'}, "Server unreachable for heartbeat.")
        return {'FINISHED'}

class SCULPTOR_OT_export_glb(bpy.types.Operator):
    bl_idname = "sculptor.export_glb"
    bl_label = "Export GLB Preview"
    bl_description = "Export active scene as binary GLTF/GLB for web preview in SculptorAI Studio"

    def execute(self, context):
        props = context.scene.sculptor_props
        import tempfile
        import os

        temp_dir = tempfile.gettempdir()
        glb_path = os.path.join(temp_dir, f"sculptor_preview_{props.active_project_id}.glb")

        try:
            # Export scene via Blender built-in gltf operator
            bpy.ops.export_scene.gltf(
                filepath=glb_path,
                export_format='GLB',
                use_selection=False,
                export_apply=True
            )
            props.last_status = "GLB Exported Successfully"
            self.report({'INFO'}, f"Preview exported: {glb_path}")
        except Exception as e:
            props.last_status = "GLB Export Failed"
            props.last_error = str(e)
            self.report({'ERROR'}, f"GLB export failed: {str(e)}")

        return {'FINISHED'}

def sculptor_heartbeat_timer():
    """
    Background timer invoked periodically by Blender's application timer loop.
    """
    try:
        # Check if scene context is available
        if bpy.context and hasattr(bpy.context, "scene") and hasattr(bpy.context.scene, "sculptor_props"):
            props = bpy.context.scene.sculptor_props
            if props.auto_heartbeat:
                status = "BUSY" if props.is_busy else "IDLE"
                SculptorApiClient.send_heartbeat(
                    status=status,
                    current_project=props.active_project_id,
                    current_execution=props.active_execution_id,
                )
    except Exception:
        pass
    return 20.0  # Run every 20 seconds

